back_end/rails/project/kaveri/config/routes.rb
Rails.application.routes.draw do
  get '/articles' => "articles#index", :as => "articles"
  get '/article/:id' => "articles#show", :as => "article"
  # put '/articles' => "article#edit", :as =>"article"

  get 'welcome/index'
  resources :articles
  # root 'welcome#index'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

back_end/rails/project/kaveri/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

back_end/rails/project/kaveri/app/models/article.rb
class Article < ApplicationRecord
	validates :title, presence: true,
                    length: { minimum: 5 }

end

back_end/rails/project/kaveri/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

back_end/rails/project/kaveri/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	before_filter :find_article, except: [:index, :new, :create]

	def new
		@article = Article.new
	end

	def edit
	end

	def create
		@article = Article.new(article_params)

		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end

	def update
		binding.pry
		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end

	def index
		@articles = Article.all
	end

	def show
	end
	private
	def article_params
		params.require(:article).permit(:title, :text, :name)
	end

	def find_article
		@article = Article.find(params[:id])
	end

end

back_end/rails/project/kaveri/app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end
  def show
  end
  def edit
  end
end

back_end/rails/project/kaveri/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

back_end/rails/project/kaveri/app/helpers/application_helper.rb
module ApplicationHelper
end

back_end/rails/project/kaveri/app/helpers/articles_helper.rb
module ArticlesHelper
end

back_end/rails/project/kaveri/app/helpers/user_helper.rb
module UserHelper
end

back_end/rails/project/kaveri/app/helpers/welcome_helper.rb
module WelcomeHelper
end

back_end/rails/project/kaveri/app/views/articles/edit.html.erb
<h1>Editing article</h1>
 
<%= form_for :assert_redirected_to :action => "index"icle, url: article_path(@article), method: :patch do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %> 

back_end/rails/project/kaveri/app/views/articles/index.html.erb
<h1>Listing articles</h1>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th>name</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
       <td><%= link_to 'Show', article_path(article) %></td> -->
       <td><%= link_to 'edit', edit_article_path(article) %></td> -->
    </tr>
  <% end %>
</table>
<%= link_to 'Back', articles_path %>

back_end/rails/project/kaveri/app/views/articles/new.html.erb
<%= form_for :article, url: articles_path do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', articles_path %>

back_end/rails/project/kaveri/app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
<p>
  <strong>Name:</strong>
  <%= @article.name %>
</p>
<%= link_to 'Back', articles_path %>

back_end/rails/project/kaveri/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kaveri</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

back_end/rails/project/kaveri/app/views/user/index.html.erb
<h1 style="color:cyan">Welcome to rails</h1>
<!-- <p>Find me in app/views/user/index.html.erb</p> -->

back_end/rails/project/kaveri/app/views/user/show.html.erb
<h1 style="color:red">This is rails</h1>

back_end/rails/project/kaveri/app/views/welcome/index.html.erb
<h1>Hello rails</h1>
<%= link_to 'My Blog', controller: 'articles' %>
<%= link_to 'New article', new_article_path %>